print("Welcome To The Band Name Generator")
city = input("What's name of the city you grew up in?\n")
pet = input("What's your pet's name?\n")
# print("Your Band Name Could Be " + city + " " + pet)
print("Your Band Name Could Be", city, pet)
